spring.cloud.stream:
  function:
    definition: bookProcessor
  bindings:
    bookProcessor-in-0:
      destination: "${BOOK_PROCESSOR_IN:raw-books}"
    bookProcessor-out-0:
      destination: "${BOOK_PROCESSOR_OUT:books}"
  kafka:
    bindings:
      bookProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bookProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers: "${KAFKA_BROKERS:localhost:9092}"
server:
  port: "${SERVER_PORT:8080}"