spring.cloud.stream:
  function:
    definition: bookProcessor
  bindings:
    bookProcessor-in-0:
      destination: raw-books
    bookProcessor-out-0:
      destination: books
  kafka:
    bindings:
      bookProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bookProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092